version: '2'
networks:
  cryptongo:
    external: True
services:
  # mongodb ------------------------------------------------
  mongodb:
    image: mongo
    container_name: crypto-mongodb
    volumes:
      - ./backup_bd/:/backup_bd/
      - ~/mongo_db/data/db-cryptongo:/data/db/
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    networks:
      cryptongo:
        aliases:
          - ${MONGODB_HOST}